 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/poke_abilities", type: :request do
  
  # PokeAbility. As you add validations to PokeAbility, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PokeAbility.create! valid_attributes
      get poke_abilities_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      poke_ability = PokeAbility.create! valid_attributes
      get poke_ability_url(poke_ability)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_poke_ability_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      poke_ability = PokeAbility.create! valid_attributes
      get edit_poke_ability_url(poke_ability)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PokeAbility" do
        expect {
          post poke_abilities_url, params: { poke_ability: valid_attributes }
        }.to change(PokeAbility, :count).by(1)
      end

      it "redirects to the created poke_ability" do
        post poke_abilities_url, params: { poke_ability: valid_attributes }
        expect(response).to redirect_to(poke_ability_url(PokeAbility.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PokeAbility" do
        expect {
          post poke_abilities_url, params: { poke_ability: invalid_attributes }
        }.to change(PokeAbility, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post poke_abilities_url, params: { poke_ability: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested poke_ability" do
        poke_ability = PokeAbility.create! valid_attributes
        patch poke_ability_url(poke_ability), params: { poke_ability: new_attributes }
        poke_ability.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the poke_ability" do
        poke_ability = PokeAbility.create! valid_attributes
        patch poke_ability_url(poke_ability), params: { poke_ability: new_attributes }
        poke_ability.reload
        expect(response).to redirect_to(poke_ability_url(poke_ability))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        poke_ability = PokeAbility.create! valid_attributes
        patch poke_ability_url(poke_ability), params: { poke_ability: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested poke_ability" do
      poke_ability = PokeAbility.create! valid_attributes
      expect {
        delete poke_ability_url(poke_ability)
      }.to change(PokeAbility, :count).by(-1)
    end

    it "redirects to the poke_abilities list" do
      poke_ability = PokeAbility.create! valid_attributes
      delete poke_ability_url(poke_ability)
      expect(response).to redirect_to(poke_abilities_url)
    end
  end
end
